#! /usr/bin/env php

<?php 

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Task manager app', '1.0');

try
{

	$pdo = new PDO('sqlite:db.sqlite');

	$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
	$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

}
catch(Exception $e)
{
	echo 'Could not connect to database';
	exit(1);
}

$dbAdapter = new App\DatabaseAdapter($pdo);

$app->add(new App\AddCommand($dbAdapter));
$app->add(new App\DeleteCommand($dbAdapter));
$app->add(new App\EditCommand($dbAdapter));
$app->add(new App\ShowCommand($dbAdapter));

$app->run();